restructured postinst-script according to new opennet-wl package, new ugw nvram var, olsr rework to fit opennet-olsrlan

diff --git a/trunk/etc/init.d/S80openvpn b/trunk/etc/init.d/S80openvpn
--- a/trunk/etc/init.d/S80openvpn
+++ b/trunk/etc/init.d/S80openvpn
@@ -15,20 +15,25 @@ test -d /var/run || mkdir -p /var/run
 
 start_vpn () {
     if [ "$NAME" = "opennet_user" ]; then
-	    on_gw="$(nvram get on_gw)"
-	    if [ -z "$on_gw" ]; then
-		echo -n " gateway not defined yet"
-		return; # wait till a gateway is found (should be done by cron.minutely)
-	    fi;
-	
-	    $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
-		    --remote $on_gw 1600 \
+	on_gw="$(nvram get on_gw)"
+	if [ -z "$on_gw" ]; then
+	    echo -n " gateway not defined yet"
+	    return; # wait till a gateway is found (should be done by cron.minutely)
+	fi;
+	$DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
+		    --remote $on_gw 1602 \
 		    --config $CONFIG_DIR/$NAME.conf \
 		    --cd $CONFIG_DIR || echo -n " FAILED->"
     else
-	    $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
-		    --config $CONFIG_DIR/$NAME.conf \
-		    --cd $CONFIG_DIR || echo -n " FAILED->"
+        on_ugw="$(nvram get on_ugw)"
+        if [ -z "$on_ugw" ]; then
+            echo -n " usergateway not defined yet"
+            return;
+        fi;
+        $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
+		--remote $on_ugw 1600 \
+                --config $CONFIG_DIR/$NAME.conf \
+		--cd $CONFIG_DIR || echo -n " FAILED->"
     fi		
     echo -n " $NAME"
 }
