we are now using two parallel usergateway-tunnels to erina and nagare.

diff --git a/trunk/etc/init.d/S80openvpn b/trunk/etc/init.d/S80openvpn
--- a/trunk/etc/init.d/S80openvpn
+++ b/trunk/etc/init.d/S80openvpn
@@ -15,15 +15,19 @@ if [ -z "$(lsmod | grep ipt_LOG)" ]; then DEBUG="false"; fi
 # one parameter, IP of usergateway
 add_fw_rules() {
 	iptables -I OUTPUT 1 -p udp --dport 1602 -o ! $WANDEV -d $1 -j DROP
-	$DEBUG && iptables -I OUTPUT 1 -p udp --dport 1602 -o ! $WANDEV -d $1 -j LOG --log-prefix "ugw wrong interface:"
-	:
+	$DEBUG && iptables -I OUTPUT 1 -p udp --dport 1602 -o ! $WANDEV -d $1 -j LOG --log-prefix "${NAME##opennet_} wrong iface:"
+	echo $1 > /var/run/openvpn.$NAME.remote_ip
 }
 
 del_fw_rules() {
-	get_rulenum() {
-		iptables -L OUTPUT --line-numbers -n -v | awk -v ddev="$WANDEV" '$5 == "udp" && $8 == "!"ddev && $12 == "dpt:1602" {print $1; exit}'
-	}
-	while $(iptables -D OUTPUT $(get_rulenum $1 $2) 2>/dev/null); do : ; done
+	if [ -e /var/run/openvpn.$NAME.remote_ip ]; then
+		remote_ip="$(cat /var/run/openvpn.$NAME.remote_ip)"
+		get_rulenum() {
+			iptables -L OUTPUT --line-numbers -n -v | awk '$5 == "udp" && $8 == "!'"$WANDEV"'" && $10 == "'"$remote_ip"'" && $12 == "dpt:1602" {print $1; exit}'
+		}
+		while $(iptables -D OUTPUT $(get_rulenum $1 $2) 2>/dev/null); do : ; done
+		rm -f /var/run/openvpn.$NAME.remote_ip
+	fi
 }
 
 start_vpn () {
@@ -39,35 +43,33 @@ start_vpn () {
 				--cd $CONFIG_DIR || echo -n " FAILED->"
 		fi
 	;;
-	"opennet_ugw")
-		on_ugw="$(nvram get on_ugw)"
-		on_ugw_ip=$(nslookup $on_ugw 2>/dev/null | tail -n 1 | awk '{ print $2 }')
-		if [ -z "$WANDEV" ]; then
-			echo -n " (WAN device not available - usergateway not available) FAILED->"
-		elif [ "$(nvram get on_share_internet)" != "on" ]; then
-			echo -n " (opennet_usergateway not activated) FAILED->"
-		elif [ -z "$on_ugw" ]; then
-			echo -n " (usergateway not defined yet) FAILED->"
-		elif [ -z "$on_ugw_ip" ]; then
-			echo -n " (can't get IP of usergateway $on_ugw) FAILED->"
-		else
-			# forbid usergateway-tunnel to use other than WAN device
-			del_fw_rules
-			add_fw_rules $on_ugw_ip
-			$DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
-				--remote $on_ugw 1602 \
-				--config $CONFIG_DIR/$NAME.conf \
-				--cd $CONFIG_DIR || (del_fw_rules && echo -n " FAILED->")
-		fi
+	"opennet_ugw1"|"opennet_ugw2")
+                on_ugw="$(nvram get on_ugws | cut -d" " -f${NAME##opennet_ugw})"
+                on_ugw_ip=$(nslookup $on_ugw 2>/dev/null | tail -n 1 | awk '{ print $2 }')
+                if [ -z "$WANDEV" ]; then
+                        echo -n " (WAN device not available - usergateway not available) FAILED->"
+                elif [ "$(nvram get on_share_internet)" != "on" ]; then
+                        echo -n " (opennet_usergateway not activated) FAILED->"
+                elif [ -z "$on_ugw" ]; then
+                        echo -n " (usergateway not defined yet) FAILED->"
+                elif [ -z "$on_ugw_ip" ]; then
+                        echo -n " (can't get IP of usergateway $on_ugw) FAILED->"
+                else
+                        # forbid usergateway-tunnel to use other than WAN device
+                        del_fw_rules
+                        add_fw_rules $on_ugw_ip
+                        $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
+                                --remote $on_ugw 1602 \
+                                --config $CONFIG_DIR/$NAME.conf \
+                                --cd $CONFIG_DIR || (del_fw_rules && echo -n " FAILED->")
+                fi
 	;;
 	esac
 	echo -n " $NAME"
 }
 
 stop_vpn () {
-	if [ "$NAME" = "opennet_ugw" ]; then
-		del_fw_rules
-	fi
+	del_fw_rules
 	kill `cat $PIDFILE` || true
 	rm $PIDFILE
 }
@@ -77,12 +79,9 @@ WANDEV=$(nvram get wan_ifname)
 case "$1" in
 start)
 	echo -n "Starting openvpn:"
-	configs="$(cd $CONFIG_DIR; ls *.conf 2> /dev/null)"
-	if test ! -z $2 ; then
-		configs="$2.conf"
-		if test ! -e $CONFIG_DIR/$configs ; then
-			echo " No such VPN: $2."; exit 1
-		fi
+	configs="$(cd $CONFIG_DIR; ls $2*.conf 2> /dev/null)"
+	if [ -z "$configs" ]; then
+		echo " No such VPN: $2."; exit 1
 	fi
 	for CONFIG in $configs; do
 		NAME=${CONFIG%%.conf}
@@ -96,56 +95,25 @@ start)
 ;;
 stop)
 	echo -n "Stopping openvpn:"
-
-	if test -z $2 ; then
-		for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
-			NAME=`echo $PIDFILE | cut -c18-`
-			NAME=${NAME%%.pid}
-			stop_vpn
-			echo -n " $NAME"
-		done
-	else
-		if test -e /var/run/openvpn.$2.pid ; then
-			PIDFILE=`ls /var/run/openvpn.$2.pid 2> /dev/null`
-			NAME=`echo $PIDFILE | cut -c18-`
-			NAME=${NAME%%.pid}
-			stop_vpn
-			echo -n " $NAME"
-		else
-			echo -n " No such VPN: $2"
-		fi
+	pidfiles="$(ls /var/run/openvpn.$2*.pid 2> /dev/null)"
+	if [ -z "$pidfiles" ]; then
+		echo " No such VPN: $2."; exit 1
 	fi
-	echo "."
-;;
-# We only 'reload' for running VPNs. New ones will only start with 'start' or 'restart'.
-reload|force-reload)
-	echo -n "Reloading openvpn:"
-	for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
+	for PIDFILE in $pidfiles; do
 		NAME=`echo $PIDFILE | cut -c18-`
 		NAME=${NAME%%.pid}
-		# If openvpn if running under a different user than root we'll need to restart
-		if egrep '^( |\t)*user' $CONFIG_DIR/$NAME.conf > /dev/null 2>&1 ; then
-			stop_vpn
-			sleep 1
-			start_vpn
-			echo -n "(restarted)"
-		else
-			kill -HUP `cat $PIDFILE` || true
-		#    start-stop-daemon --stop --signal HUP --quiet --oknodo \
-		#      --exec $DAEMON --pidfile $PIDFILE
-			echo -n " $NAME"
-		fi
+		stop_vpn
+		echo -n " $NAME"
 	done
 	echo "."
-	;;
-
+;;
 restart)
 	$0 stop $2
 	sleep 1
 	$0 start $2
 	;;
 *)
-	echo "Usage: $0 {start|stop|reload|restart|force-reload}" >&2
+	echo "Usage: $0 {start|stop|restart}" >&2
 	exit 1
 	;;
 esac
