modified to start only opennet_user-tunnel if called without second argument

diff --git a/trunk/etc/init.d/S80openvpn b/trunk/etc/init.d/S80openvpn
--- a/trunk/etc/init.d/S80openvpn
+++ b/trunk/etc/init.d/S80openvpn
@@ -5,6 +5,9 @@
 # Modified for openvpn by Alberto Gonzalez Iniesta <agi@agi.as>
 # Modified for restarting / starting / stopping single tunnels by Richard Mueller <mueller@teamix.net>
 
+# modified to start/stop only opennet_user if called without second argument
+# reload works still on all running openvpn-instances
+
 test $DEBIAN_SCRIPT_DEBUG && set -v -x
 
 DAEMON=/usr/sbin/openvpn
@@ -14,16 +17,22 @@ test -d $CONFIG_DIR || exit 0
 test -d /var/run || mkdir -p /var/run
 
 start_vpn () {
-    on_gw="$(nvram get on_gw)"
-    if [ -z "$on_gw" ]; then
-	echo -n " gateway not defined yet"
-	return; # wait till a gateway is found (should be done by cron.minutely)
-    fi;
-
-    $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
-            --remote $on_gw 1600 \
-	    --config $CONFIG_DIR/$NAME.conf \
-	    --cd $CONFIG_DIR || echo -n " FAILED->"
+    if [ "$NAME" = "opennet_user" ]; then
+	    on_gw="$(nvram get on_gw)"
+	    if [ -z "$on_gw" ]; then
+		echo -n " gateway not defined yet"
+		return; # wait till a gateway is found (should be done by cron.minutely)
+	    fi;
+	
+	    $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
+		    --remote $on_gw 1600 \
+		    --config $CONFIG_DIR/$NAME.conf \
+		    --cd $CONFIG_DIR || echo -n " FAILED->"
+    else
+	    $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
+		    --config $CONFIG_DIR/$NAME.conf \
+		    --cd $CONFIG_DIR || echo -n " FAILED->"
+    fi		
     echo -n " $NAME"
 }
 stop_vpn () {
@@ -33,13 +42,15 @@ stop_vpn () {
 
 case "$1" in
 start)
+  if test -z $2 ; then echo "S80openvpn called without second argument. Only changing opennet_user tunnel."; fi
   echo -n "Starting openvpn:"
 
   if test -z $2 ; then
-    for CONFIG in `cd $CONFIG_DIR; ls *.conf 2> /dev/null`; do
-      NAME=${CONFIG%%.conf}
+    #for CONFIG in `cd $CONFIG_DIR; ls *.conf 2> /dev/null`; do
+      #NAME=${CONFIG%%.conf}
+      NAME="opennet_user"
       start_vpn
-    done
+    #done
   else
     if test -e $CONFIG_DIR/$2.conf ; then
       NAME=$2
@@ -52,15 +63,17 @@ start)
 
   ;;
 stop)
+  if test -z $2 ; then echo "S80openvpn called without second argument. Only changing opennet_user tunnel."; fi
   echo -n "Stopping openvpn:"
 
   if test -z $2 ; then
-    for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
+    #for PIDFILE in `ls /var/run/openvpn.*.pid 2> /dev/null`; do
+      PIDFILE=`ls /var/run/openvpn.opennet_user.pid 2> /dev/null`
       NAME=`echo $PIDFILE | cut -c18-`
       NAME=${NAME%%.pid}
       stop_vpn
       echo -n " $NAME"
-    done
+    #done
   else
     if test -e /var/run/openvpn.$2.pid ; then
       PIDFILE=`ls /var/run/openvpn.$2.pid 2> /dev/null`
